[package]
name = "wasm_test"
version = "0.1.0"
authors = ["Thiago M. Nóbrega <42742390+mmtmn@users.noreply.github.com>"]
edition = "2018"

[lib]
create-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.63"